version: '3.3'

services:

  acpc-back:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: acpc_2023
    volumes:
      - pg_data:/var/lib/postgresql/data

  acpc-front:
    container_name: frontend
    build:
      context: ../client-side
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - acpc-back

volumes:
  pg_data:
